name: bookabook
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  http:
  shared_preferences: ^0.5.1+1
  carousel_slider: ^1.3.0
  cached_network_image: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
      - family: Raleway
        fonts:
          - asset: res/fonts/raleway/Raleway-Regular.ttf
          - asset: res/fonts/raleway/Raleway-Italic.ttf
            style: italic
  uses-material-design: true
  assets:
    - res/images/loginbg.png
    - res/placeholder.jpg